insert into constants values(1,'DEUTERIUM_BASE_ENEMY_ARMY',26000);
insert into constants values(2,'METAL_BASE_ENEMY_ARMY',180000);
insert into constants values(3,'ENEMY_FLEET_INCREASE',6);
insert into constants values(4,'PLANET_DEUTERIUM_GENERATED', 1500);
insert into constants values(5,'PLANET_METAL_GENERATED',5000);
insert into constants values(6,'UPGRADE_BASE_DEFENSE_TECHNOLOGY_DEUTERIUM_COST',2000);
insert into constants values(7,'UPGRADE_BASE_ATTACK_TECHNOLOGY_DEUTERIUM_COST',2000);
insert into constants values(8,'UPGRADE_PLUS_DEFENSE_TECHNOLOGY_DEUTERIUM_COST',60);
insert into constants values(9,'UPGRADE_PLUS_ATTACK_TECHNOLOGY_DEUTERIUM_COST',60);
insert into constants values(10,'UPGRADE_PLUS_DEFENSE_TECHNOLOGY_DEUTERIUM_COST',60);
insert into constants values(11,'UPGRADE_PLUS_ATTACK_TECHNOLOGY_DEUTERIUM_COST',60);
insert into constants values(12,'METAL_COST_LIGTHHUNTER',3000);
insert into constants values(13,'METAL_COST_HEAVYHUNTER',6500);
insert into constants values(14,'METAL_COST_BATTLESHIP',45000);
insert into constants values(15,'METAL_COST_ARMOREDSHIP',30000);
insert into constants values(16,'DEUTERIUM_COST_LIGTHHUNTER', 50);
insert into constants values(17,'DEUTERIUM_COST_HEAVYHUNTER',50);
insert into constants values(18,'DEUTERIUM_COST_BATTLESHIP',7000);
insert into constants values(19,'DEUTERIUM_COST_ARMOREDSHIP',15000);
insert into constants values(20,'DEUTERIUM_COST_MISSILELAUNCHER',0);
insert into constants values(21,'DEUTERIUM_COST_IONCANNON',500);
insert into constants values(22,'DEUTERIUM_COST_PLASMACANNON',5000);
insert into constants values(23, 'METAL_COST_LIGTHHUNTER', 3000);
insert into constants values(24, 'METAL_COST_HEAVYHUNTER', 6500);
insert into constants values(25, 'METAL_COST_BATTLESHIP', 45000);
insert into constants values(26, 'METAL_COST_ARMOREDSHIP', 30000);
insert into constants values(27, 'DEUTERIUM_COST_LIGTHHUNTER', 50);
insert into constants values(28, 'DEUTERIUM_COST_HEAVYHUNTER', 50);
insert into constants values(29, 'DEUTERIUM_COST_BATTLESHIP', 7000);
insert into constants values(30, 'DEUTERIUM_COST_ARMOREDSHIP', 15000);
insert into constants values(31, 'DEUTERIUM_COST_MISSILELAUNCHER', 0);
insert into constants values(32, 'DEUTERIUM_COST_IONCANNON', 500);
insert into constants values(33, 'DEUTERIUM_COST_PLASMACANNON', 5000);
insert into constants values(34, 'METAL_COST_MISSILELAUNCHER', 2000);
insert into constants values(35, 'METAL_COST_IONCANNON', 4000);
insert into constants values(36, 'METAL_COST_PLASMACANNON', 50000);
insert into constants values(37, 'BASE_DAMAGE_LIGTHHUNTER', 80);
insert into constants values(38, 'BASE_DAMAGE_HEAVYHUNTER', 150);
insert into constants values(39, 'BASE_DAMAGE_BATTLESHIP', 1000);
insert into constants values(40, 'BASE_DAMAGE_ARMOREDSHIP', 700);
insert into constants values(41, 'BASE_DAMAGE_MISSILELAUNCHER', 80);
insert into constants values(42, 'BASE_DAMAGE_IONCANNON', 250);
insert into constants values(43, 'BASE_DAMAGE_PLASMACANNON', 2000);
insert into constants values(44, 'REDUCTION_DEFENSE_IONCANNON', 100);
insert into constants values(45, 'ARMOR_LIGTHHUNTER', 400);
insert into constants values(46, 'ARMOR_HEAVYHUNTER', 1000);
insert into constants values(47, 'ARMOR_BATTLESHIP', 6000);
insert into constants values(48, 'ARMOR_ARMOREDSHIP', 8000);
insert into constants values(49, 'ARMOR_MISSILELAUNCHER', 200);
insert into constants values(50, 'ARMOR_IONCANNON', 1200);
insert into constants values(51, 'ARMOR_PLASMACANNON', 7000);
insert into constants values(52, 'PLUS_ARMOR_LIGTHHUNTER_BY_TECHNOLOGY', 5);
insert into constants values(53, 'PLUS_ARMOR_HEAVYHUNTER_BY_TECHNOLOGY', 5);
insert into constants values(54, 'PLUS_ARMOR_BATTLESHIP_BY_TECHNOLOGY', 5);
insert into constants values(55, 'PLUS_ARMOR_ARMOREDSHIP_BY_TECHNOLOGY', 5);
insert into constants values(56, 'PLUS_ARMOR_MISSILELAUNCHER_BY_TECHNOLOGY', 5);
insert into constants values(57, 'PLUS_ARMOR_IONCANNON_BY_TECHNOLOGY', 5);
insert into constants values(58, 'PLUS_ARMOR_PLASMACANNON_BY_TECHNOLOGY', 5);
insert into constants values(59, 'PLUS_ATTACK_LIGTHHUNTER_BY_TECHNOLOGY', 5);
insert into constants values(60, 'PLUS_ATTACK_HEAVYHUNTER_BY_TECHNOLOGY', 5);
insert into constants values(61, 'PLUS_ATTACK_BATTLESHIP_BY_TECHNOLOGY', 5);
insert into constants values(62, 'PLUS_ATTACK_ARMOREDSHIP_BY_TECHNOLOGY', 5);
insert into constants values(63, 'PLUS_ATTACK_MISSILELAUNCHER_BY_TECHNOLOGY', 5);
insert into constants values(64, 'PLUS_ATTACK_IONCANNON_BY_TECHNOLOGY', 5);
insert into constants values(65, 'PLUS_ATTACK_PLASMACANNON_BY_TECHNOLOGY', 5);
insert into constants values(66, 'CHANCE_GENERATNG_WASTE_LIGTHHUNTER', 55);
insert into constants values(67, 'CHANCE_GENERATNG_WASTE_HEAVYHUNTER', 65);
insert into constants values(68, 'CHANCE_GENERATNG_WASTE_BATTLESHIP', 80);
insert into constants values(69, 'CHANCE_GENERATNG_WASTE_ARMOREDSHIP', 90);
insert into constants values(70, 'CHANCE_GENERATNG_WASTE_MISSILELAUNCHER', 55);
insert into constants values(71, 'CHANCE_GENERATNG_WASTE_IONCANNON', 65);
insert into constants values(72, 'CHANCE_GENERATNG_WASTE_PLASMACANNON', 75);
insert into constants values(73, 'CHANCE_ATTACK_AGAIN_LIGTHHUNTER', 3);
insert into constants values(74, 'CHANCE_ATTACK_AGAIN_HEAVYHUNTER', 7);
insert into constants values(75, 'CHANCE_ATTACK_AGAIN_BATTLESHIP', 45);
insert into constants values(76, 'CHANCE_ATTACK_AGAIN_ARMOREDSHIP', 70);
insert into constants values(77, 'CHANCE_ATTACK_AGAIN_MISSILELAUNCHER', 5);
insert into constants values(78, 'CHANCE_ATTACK_AGAIN_IONCANNON', 12);
insert into constants values(79, 'CHANCE_ATTACK_AGAIN_PLASMACANNON', 30);
insert into constants values(80, 'CHANCE_ATTACK_PLANET_UNITS_1', 5);
insert into constants values(81, 'CHANCE_ATTACK_PLANET_UNITS_2', 10);
insert into constants values(82, 'CHANCE_ATTACK_PLANET_UNITS_3', 15);
insert into constants values(83, 'CHANCE_ATTACK_PLANET_UNITS_4', 40);
insert into constants values(84, 'CHANCE_ATTACK_PLANET_UNITS_5', 5);
insert into constants values(85, 'CHANCE_ATTACK_PLANET_UNITS_6', 10);
insert into constants values(86, 'CHANCE_ATTACK_PLANET_UNITS_7', 15);
insert into constants values(87, 'CHANCE_ATTACK_ENEMY_UNITS_1', 10);
insert into constants values(88, 'CHANCE_ATTACK_ENEMY_UNITS_2', 20);
insert into constants values(89, 'CHANCE_ATTACK_ENEMY_UNITS_3', 30);
insert into constants values(90, 'CHANCE_ATTACK_ENEMY_UNITS_4', 40);
insert into constants values(91, 'PERCENTATGE_WASTE', 70);