SET SERVEROUTPUT ON

DECLARE
BEGIN
Initialize;
/*
INSERT INTO "USER" VALUES(1, 'Manolo', '1234', TO_DATE('12/4/1990', 'DD/MM/YYYY'));
INSERT INTO "USER" VALUES(2, 'Pepe', 'qwerty', TO_DATE('2/1/1992', 'DD/MM/YYYY'));
INSERT INTO "USER" VALUES(3, 'Pepe2', 'qwerty', TO_DATE('2/1/1992', 'DD/MM/YYYY'));
*/
END;


