CREATE OR REPLACE PROCEDURE INITIALIZE

IS

BEGIN

DROP_TABLE;
DBMS_OUTPUT.PUT_LINE('');
CREATE_TABLE;
DBMS_OUTPUT.PUT_LINE('');
INSERT_DATA;

EXCEPTION

WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('Error en el proceso INITIALIZE:');
DBMS_OUTPUT.PUT_LINE('Descripcion del error: '||SQLERRM);

END;